name: Build

on:
  push:
    branches:
      - '*'

jobs:
  build-windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Compile
        run: |
          curl -O https://dl-game-sdk.discordapp.net/3.2.1/discord_game_sdk.zip
          unzip -o discord_game_sdk.zip -d .
          ruby ./extconf.rb x86_64
          make

      - name: Artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ github.job }}
          path: discord.so

  build-linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Compile
        run: |
          curl -O https://dl-game-sdk.discordapp.net/3.2.1/discord_game_sdk.zip
          unzip -o discord_game_sdk.zip -d .
          ruby ./extconf.rb x86_64
          make

      - name: Artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ github.job }}
          path: discord.so

  build-macos:
    name: macOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Compile
        run: |
          curl -O https://dl-game-sdk.discordapp.net/3.2.1/discord_game_sdk.zip
          unzip -o discord_game_sdk.zip -d .
          ruby ./extconf.rb x86_64
          make
          cp discord.bundle discord.x86_64
          make clean
          ruby ./extconf.rb arm64
          make
          cp discord.bundle discord.arm64
          lipo -create -output discord.bundle discord.x86_64 discord.arm64
          lipo -create -output discord_game_sdk.dylib ./lib/x86_64/libdiscord_game_sdk.dylib ./lib/arm64/libdiscord_game_sdk.dylib
          LIBRUBY=`otool -L discord.bundle | grep libruby | awk '{print $1}'`
          install_name_tool -change $LIBRUBY @rpath/`echo $LIBRUBY | sed 's~.*/~~'` discord.bundle

      - name: Artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ github.job }}
          path: discord.bundle
