name: Build

on:
  push:
    branches:
      - '*'

jobs:
  build-windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Compile
        run: |
          ruby ./extconf.rb
          make

      - name: Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.job }}
          path: *

  build-linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Compile
        run: |
          ruby ./extconf.rb
          make

      - name: Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.job }}
          path: *

  build-macos:
    name: macOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Compile
        run: |
          ruby ./extconf.rb
          make
          lipo -archs discord.bundle

      - name: Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.job }}
          path: *
